### ISSUE TITLE
悬浮窗场景如何支持

### ISSUE THREAD

**Issue by xiaopengs** [DSAppTeam/PanelSwitchHelper#117]
例如：虎牙开播工具，在系统之上的悬浮窗，需要有输入键盘支持

**Comment by YummyLau** [comment]
@xiaopengs 能否提供一下截图或者场景。如果是系统级的分屏，目前没有适配的。适配的时软键盘的主动悬浮。

**Comment by LinXueyuanStdio** [comment]
@YummyLau 比如一个全屏的悬浮窗，用service+windowManager.addView实现，完全抛弃activity。这样获取不到window了，也无法构建Builder对象了。

**Comment by LinXueyuanStdio** [comment]
看了一下源码，感觉只需要windowManager和rootView就足够了，可以不用依赖 window
1. DeviceRuntime里window.decorView的地方换成rootView，window flag的地方用windowManager
2. DisplayUtil里都可以用windowManager和rootView来替换window

**Comment by YummyLau** [comment]
@LinXueyuanStdio 在输入法的切换场景高度兼容是一个难题。 可 fork 改下提供思路，我clone下来看下。

**Comment by HeroZ-Dodge** [comment]
v1.5.0 添加了悬浮弹窗场景下的用例
