### ISSUE TITLE
表情面板显示时 点击输入框，表情面板立即变空白

### ISSUE THREAD

**Issue by farsunset** [DSAppTeam/PanelSwitchHelper#167]
Android 12   一加9pro
表情面板显示时 点击输入框，表情面板立即变空白，然后才是键盘弹起来
这个地方需要优化一下

**Comment by HeroZ-Dodge** [comment]
由于 softInputMode = SOFT_INPUT_ADJUST_RESIZE，所以键盘弹起时 decorView 的高度发生变化，导致表情面板可显示的高度变成0。

在Android 12 之后，我们会支持 softInputMode = SOFT_INPUT_ADJUST_NOTHING ，通过监听键盘过渡动画的方式（ViewCompat.setWindowInsetsAnimationCallback）来调整面板高度，可以达到你想要的效果。
