### ISSUE TITLE
dialogFragment有问题

### ISSUE THREAD

**Issue by chenkexu** [DSAppTeam/PanelSwitchHelper#168]
https://user-images.githubusercontent.com/14785825/162864304-703f9510-9d6a-460f-8756-cd9c5864e8df.mp4

dialogfragment 点击输入框无法调出键盘，闪动

小米11  Android 12

**Comment by YaCZHong** [comment]
我也是Android 12遇到这个问题

**Comment by YaCZHong** [comment]
给dialog的window设置softInputMode = WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE即可
