### ISSUE TITLE
Recycleview在最下面一屏的时候，把item滑动到倒数第二条的位置，直接点击表情按钮会发生回弹，表情界面会弹出再缩回

### ISSUE THREAD

**Issue by HandSomeMaster** [DSAppTeam/PanelSwitchHelper#173]
补充一下 准确来说 是在recycleview最下面一屏的时候都这样，还有一个操作就是在弹出表情界面的时候同时调用recycleview滑动到底部的方法 这两个同时存在的时候 就会出现这个bug  不过在列表拉到最下面的时候不会出现 希望能解决这个问题

**Comment by HeroZ-Dodge** [comment]
> 补充一下 准确来说 是在recycleview最下面一屏的时候都这样，还有一个操作就是在弹出表情界面的时候同时调用recycleview滑动到底部的方法 这两个同时存在的时候 就会出现这个bug 不过在列表拉到最下面的时候不会出现 希望能解决这个问题

感谢你的反馈，我们将会在下一个小版本(预计 v1.5.1)修复这个问题。
