### ISSUE TITLE
聊天页面点击切换表情的按钮，recycleview的内容会上下乱跳

### ISSUE THREAD

**Issue by sangsais** [DSAppTeam/PanelSwitchHelper#178]
问题现象

聊天场景中，recyclewview + 底部输入view（输入框 表情按钮），当列表数据只有1条2条，铺不满屏幕的时候，来回点击表情按钮呼出隐藏表情面板，列表数据会上下乱跳。

依赖版本： implementation 'com.github.DSAppTeam:PanelSwitchHelper:v1.5.2'

可以复现的类：
1 ChatCusContentScrollActivity
2 ChatActivity

**Comment by HeroZ-Dodge** [comment]
你的 Android 版本是多少

**Comment by sangsais** [comment]
手机型号 MI8 SE
MIUI版本 10.3
Android 版本 9

**Comment by sangsais** [comment]
红米NOTE7上跑demo，
第一次点击表情按钮呼出然后隐藏表情面板，列表数据没有上下跳，
第二次点击呼出隐藏就开始乱跳了。

我重新装了demo在华为手机上跑也是跟红米NOTE7一样的现象
设备 HONOR 9X 型号 HLK-AL00
HarmonyOS版本 2.0.0

**Comment by HeroZ-Dodge** [comment]
demo是用当前最新代码打包的吗，我刚才找了几个类似的手机，没有遇到这个情况，或者你能加下我们群，方便沟通
![image](https://user-images.githubusercontent.com/10356753/196859522-395b7bd4-3be8-4419-b7aa-0d65d59beba2.png)

**Comment by sangsais** [comment]
拉了最新代码，没有在DEMO复现了，之前的本地代码是1.5.0的版本。
但是我自己项目依赖的是1.5.2的版本，在我项目了还是会跳来跳去，代码跟DEMO里的ChatActivity的代码是一样的，奇怪。

**Comment by HeroZ-Dodge** [comment]
https://github.com/DSAppTeam/PanelSwitchHelper/issues/173
之前是修复了这个问题，你说的上下乱跳，是指面板弹窗后又自动关闭这个问题吗

**Comment by sangsais** [comment]
使用此版本 api 'com.github.DSAppTeam:PanelSwitchHelper:v1.4.0' 问题解决 感谢
