### ISSUE TITLE
两个编辑框，焦点错乱

### ISSUE THREAD

**Issue by chenkexu** [DSAppTeam/PanelSwitchHelper#179]
在页面中有两个输入法时，有两个问题：

1、输入法的焦点在顶部编辑框上，但是点击弹出键盘，焦点跑到了下面的编辑框上
2、选择某个表情时，永远是添加到底部的编辑框中（demo代码可能有问题）

见以下视频：

https://user-images.githubusercontent.com/14785825/197332810-58267380-1a12-4816-ac48-b683bdab5831.mp4

**Comment by HeroZ-Dodge** [comment]
添加了 EditTextSelector 接口，用于选中对应的EditText ，emoji面板属于具体业务的实现，这里只是提供一种思路
