### ISSUE TITLE
如果输入框上面还有视图得话，列表偏移位置不准确

### ISSUE THREAD

**Issue by BianXiaoYan** [DSAppTeam/PanelSwitchHelper#186]
Androidx版本：是
PanelSwitchHelper版本：v1.5.2
手机型号:小米12Pro
手机系统版本： Android 13
问题描述：譬如那种回复消息功能，被回复得内容显示输入框得上方，这是列表偏移位置没有正确，导致有消息部分被回复视图遮挡住了
有问题显示得截图
![屏幕截图 2023-03-11 163536](https://user-images.githubusercontent.com/19401417/224474322-17147980-3ca8-4cdd-9663-5b3c5b9c02fe.png)
正常样子显示效果
![屏幕截图 2023-03-11 163608](https://user-images.githubusercontent.com/19401417/224474395-6dfb373e-89a6-4d16-8e44-769f404db801.png)
回复视图样式
![屏幕截图 2023-03-11 163715](https://user-images.githubusercontent.com/19401417/224474419-2677cba3-c3c3-4a92-9af2-c5b4d4c46f60.png)
@YummyLau

**Comment by HeroZ-Dodge** [comment]
你可以试试1.5.3的版本，看看这个问题是否能解决

**Comment by BianXiaoYan** [comment]
> 

更新到1.5.3版本啦还是会覆盖列表内容。

**Comment by BianXiaoYan** [comment]
> 你可以试试1.5.3的版本，看看这个问题是否能解决
更新到1.5.3版本啦还是会覆盖列表内容。

**Comment by HeroZ-Dodge** [comment]
你这边是否方便给我们提个pull request，复现下你这边遇到的情况，我后续调试看看

**Comment by BianXiaoYan** [comment]
> 你这边是否方便给我们提个pull request，复现下你这边遇到的情况，我后续调试看看

ok我创建一个例子pull上来

**Comment by BianXiaoYan** [comment]
> > 你这边是否方便给我们提个pull request，复现下你这边遇到的情况，我后续调试看看
> 
> ok我创建一个例子pull上来

我已经pull request  长按消息显示回复视图，麻烦请查看 @HeroZ-Dodge @YummyLau

**Comment by HeroZ-Dodge** [comment]
![image](https://user-images.githubusercontent.com/10356753/229073959-67bc6dae-8297-4a8d-a599-28acd38e0e00.png)
demo现在运行的效果不是你想要的吗

**Comment by HeroZ-Dodge** [comment]
![image](https://user-images.githubusercontent.com/10356753/229076750-f4505f55-be81-48ad-a47e-35e38271a07e.png)
当“回复某某某”这控件显示的时候，RecyclerView的控件的高度是红色区域了，如果你想要滚动到最底部，需要你用代码控制滚动

**Comment by HeroZ-Dodge** [comment]
![image](https://user-images.githubusercontent.com/10356753/231143085-fb0fe850-4f74-41a4-a97e-de1111df117c.png)
方便的话，来交流群沟通吧
