### ISSUE TITLE
PanelSwitchHelper同时存在于Activity和dialog时，导致Activity上的PanelSwitchHelper无法监听

### ISSUE THREAD

**Issue by smileToWxm** [DSAppTeam/PanelSwitchHelper#190]
Androidx版本：是
PanelSwitchHelper版本：v1.5.3
手机型号: 小米12s
手机系统版本： Android 12
问题描述：Activity布局内有一个PanelSwitchHelper，还有一个按钮，点击按钮弹出一个dialog，dialog内部也有一个PanelSwitchHelper，关闭dialog后，Activity的PanelSwitchHelper就会出现软键盘监听异常，高度不正确，且再用hookSystemBackByPanelSwitcher关闭时，关闭不了软键盘
场景复现：demo也会出现这个问题，场景复现如下： PhoneDouyinLiveActivity内新增一个按钮的点击事件，点击事件里面代码如下
   DialogFragment dialogFragment = new ChatDialogFragment();
    dialogFragment.showNow(getSupportFragmentManager(), "dialogFragment");关闭对话框之后再次点击 PhoneDouyinLiveActivity内的软键盘就会出现异常
Log提供：
日志如下：
17:56:20.387 PhoneDouyinLiveActivity   D  输入框是否获得焦点 : true
17:56:20.388 LogTracker                D  OnEditFocusChangeListener#onFocusChange => EditText has focus ( true )
17:56:20.389 InputMethodManager        D  showSoftInput() view=androidx.appcompat.widget.AppCompatEditText{686713d VFED..CL. .F....ID 26,0-844,105 #7f0700a8 app:id/input aid=1073741825} flags=0 reason=SHOW_SOFT_INPUT
17:56:20.392 LogTracker                D  PanelSwitchLayout#checkoutPanel => checkout success ! lastPanel's id : -1 , panel's id :0
17:56:20.392 PhoneDouyinLiveActivity   D  唤起系统输入法
17:56:20.392 LogTracker                D  OnPanelChangeListener#onKeyboard => panel： keyboard
17:56:20.397 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.407 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.420 InsetsController          D  show(ime(), fromIme=true)
17:56:20.422 LogTracker                D  PanelSwitchLayout#WindowInsetsListener => KeyBoardHeight : 765，isShow true
17:56:20.422 LogTracker                D  PanelSwitchLayout#KeyboardStateChanged => try to set KeyBoardHeight : 765，isShow true
17:56:20.422 LogTracker                D  PanelUtil#onGlobalLayout => current KeyBoardHeight is equal，just ignore！
17:56:20.422 LogTracker                D  PanelSwitchLayout#checkoutPanel => checkout success ! lastPanel's id : -1 , panel's id :0
17:56:20.422 ChatDialogFragment        D  唤起系统输入法
17:56:20.422 LogTracker                D  OnPanelChangeListener#onKeyboard => panel： keyboard
17:56:20.422 ChatDialogFragment        D  系统键盘是否可见 : true 高度为：765
17:56:20.422 LogTracker                D  OnKeyboardStateListener#onKeyboardChange => Keyboard is showing ( true ),height is 765
17:56:20.422 LogTracker                D  PanelSwitchLayout#WindowInsetsListener => requestLayout
17:56:20.425 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.426 LogTracker                D  onStart => keyboard height = 889
17:56:20.426 LogTracker                D  onStart => realKeyboardH height = 765
17:56:20.427 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.427 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.0 
                                          softInputHeight                                    = 0 
                                          decorView.bottom                                   = 2319 
17:56:20.430 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.430 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.0 
                                          softInputHeight                                    = 0 
                                          decorView.bottom                                   = 2319 
17:56:20.438 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.439 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.028070176 
                                          softInputHeight                                    = 7 
                                          decorView.bottom                                   = 2319 
17:56:20.447 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.447 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.05964912 
                                          softInputHeight                                    = 38 
                                          decorView.bottom                                   = 2319 
17:56:20.455 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.455 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.0877193 
                                          softInputHeight                                    = 102 
                                          decorView.bottom                                   = 2319 
17:56:20.464 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.464 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.11578947 
                                          softInputHeight                                    = 194 
                                          decorView.bottom                                   = 2319 
17:56:20.472 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.472 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.14385965 
                                          softInputHeight                                    = 291 
                                          decorView.bottom                                   = 2319 
17:56:20.480 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.480 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.1754386 
                                          softInputHeight                                    = 383 
                                          decorView.bottom                                   = 2319 
17:56:20.488 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.489 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.20350876 
                                          softInputHeight                                    = 451 
                                          decorView.bottom                                   = 2319 
17:56:20.497 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.497 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.23157895 
                                          softInputHeight                                    = 505 
                                          decorView.bottom                                   = 2319 
17:56:20.505 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.506 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.25964913 
                                          softInputHeight                                    = 552 
                                          decorView.bottom                                   = 2319 
17:56:20.513 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.514 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.29122806 
                                          softInputHeight                                    = 599 
                                          decorView.bottom                                   = 2319 
17:56:20.522 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.522 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.31929824 
                                          softInputHeight                                    = 634 
                                          decorView.bottom                                   = 2319 
17:56:20.530 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.530 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.34736842 
                                          softInputHeight                                    = 664 
                                          decorView.bottom                                   = 2319 
17:56:20.538 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.538 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.3754386 
                                          softInputHeight                                    = 691 
                                          decorView.bottom                                   = 2319 
17:56:20.546 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.546 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.40701753 
                                          softInputHeight                                    = 718 
                                          decorView.bottom                                   = 2319 
17:56:20.554 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.554 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.4350877 
                                          softInputHeight                                    = 739 
                                          decorView.bottom                                   = 2319 
17:56:20.562 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.563 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.4631579 
                                          softInputHeight                                    = 758 
                                          decorView.bottom                                   = 2319 
17:56:20.571 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.571 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.49122807 
                                          softInputHeight                                    = 775 
                                          decorView.bottom                                   = 2319 
17:56:20.579 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.579 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.522807 
                                          softInputHeight                                    = 791 
                                          decorView.bottom                                   = 2319 
17:56:20.587 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.587 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.5508772 
                                          softInputHeight                                    = 805 
                                          decorView.bottom                                   = 2319 
17:56:20.596 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.596 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.57894737 
                                          softInputHeight                                    = 817 
                                          decorView.bottom                                   = 2319 
17:56:20.604 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.604 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.6070175 
                                          softInputHeight                                    = 828 
                                          decorView.bottom                                   = 2319 
17:56:20.612 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.612 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.6385965 
                                          softInputHeight                                    = 838 
                                          decorView.bottom                                   = 2319 
17:56:20.620 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.621 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.6666667 
                                          softInputHeight                                    = 847 
                                          decorView.bottom                                   = 2319 
17:56:20.629 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.629 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.69473684 
                                          softInputHeight                                    = 854 
                                          decorView.bottom                                   = 2319 
17:56:20.637 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.637 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.722807 
                                          softInputHeight                                    = 861 
                                          decorView.bottom                                   = 2319 
17:56:20.645 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.645 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.75438595 
                                          softInputHeight                                    = 867 
                                          decorView.bottom                                   = 2319 
17:56:20.653 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.653 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.78245616 
                                          softInputHeight                                    = 872 
                                          decorView.bottom                                   = 2319 
17:56:20.661 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.661 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.8105263 
                                          softInputHeight                                    = 876 
                                          decorView.bottom                                   = 2319 
17:56:20.671 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.671 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.83859646 
                                          softInputHeight                                    = 880 
                                          decorView.bottom                                   = 2319 
17:56:20.678 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.678 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.8701754 
                                          softInputHeight                                    = 882 
                                          decorView.bottom                                   = 2319 
17:56:20.687 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.687 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.89824563 
                                          softInputHeight                                    = 885 
                                          decorView.bottom                                   = 2319 
17:56:20.694 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.694 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.9263158 
                                          softInputHeight                                    = 886 
                                          decorView.bottom                                   = 2319 
17:56:20.703 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.703 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.95789474 
                                          softInputHeight                                    = 887 
                                          decorView.bottom                                   = 2319 
17:56:20.711 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.711 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 0.9859649 
                                          softInputHeight                                    = 888 
                                          decorView.bottom                                   = 2319 
17:56:20.719 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:20.719 LogTracker                D  onProgress => keyboard animation progress 
                                          fraction                                           = 1.0 
                                          softInputHeight                                    = 889 
                                          decorView.bottom                                   = 2319 
17:56:21.907 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:21.922 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:26.915 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:26.924 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:31.913 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765
17:56:31.927 LogTracker                D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :765

**Comment by smileToWxm** [comment]
找到解决方案了， 使用 dialogFragment、popupWindow的时候 在初始化 PanelSwitchHelper.Builder时需要添加   setWindowInsetsRootView(binding.panelSwitchLayout.getRootView()) 这句话。
原因是 PanelSwitchLayout在 注册 setOnApplyWindowInsetsListener的时候传入的rootView是  
val rootView = windowInsetsRootView ?: window.decorView.rootView，而在最后 releaseKeyboardChangedListener 注销监听的时候 传入的却是 rootView（这个rootView是panelSwitchLayout本身）所以就会出现 虽然dialogFragment、popupWindow关闭了 但是监听还存在，这样回到 Activity层的时候 就会导致监听被拦截。
仅在Activity上使用不会出现这个问题，是因为 window.decorView.rootView 和 panelSwitchLayout.getRootView是同一个所以不会出现问题

**Comment by HeroZ-Dodge** [comment]
刚才review了下代码，原因应该是 Activity 和DialogFragment 在初始的时候，ViewCompat.setOnApplyWindowInsetsListener(view)传的这个view是同一个对象，导致Activity的监听被覆盖了，所以在dialogFragment初始的时候setWindowInsetsRootView，可以避免activity的监听被覆盖。

**Comment by HeroZ-Dodge** [comment]
最后在 ViewCompat.setOnApplyWindowInsetsListener(rootView, null) 释放监听的时候，这里不够严谨，应该改成
```
            val rootView = windowInsetsRootView ?: window.decorView.rootView
            ViewCompat.setOnApplyWindowInsetsListener(rootView, null)
```
会更合理些
感谢提出的反馈
