### ISSUE TITLE
自定义EditText 不弹出键盘

### ISSUE THREAD

**Issue by YUHAN-GUO** [DSAppTeam/PanelSwitchHelper#192]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/43516357/232363356-a930ce99-6f51-437c-8b0c-93d5c8c43e00.png">
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/43516357/232363399-50a473d4-424d-4dea-9e7b-92ff30415cce.png">
加入这两行后 正常弹出

**Comment by HeroZ-Dodge** [comment]
感谢你的反馈
