### ISSUE TITLE
1.5.4版本依赖下载不下来,试了下1.5.3版本就可以正常下载

### ISSUE THREAD

**Issue by protectedMan** [DSAppTeam/PanelSwitchHelper#195]
> Could not resolve all files for configuration ':desk:lezhuDevelopmentDebugRuntimeClasspath'.
   > Could not find com.github.DSAppTeam:PanelSwitchHelper:v1.5.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
       - https://maven.aliyun.com/nexus/content/groups/public/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
       - https://maven.aliyun.com/nexus/content/repositories/releases/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
       - https://mvn.getui.com/nexus/content/repositories/releases/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
       - https://dl.google.com/dl/android/maven2/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
       - https://www.jitpack.io/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
       - https://gitee.com/goweii/maven-repository/raw/master/releases/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
       - https://repo1.maven.org/maven2/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
       - file:/Users/hailong/StudioProjects/lezhu2/lezhu-common/libs/PanelSwitchHelper-v1.5.4.jar
       - file:/Users/hailong/StudioProjects/lezhu2/lezhu-common/libs/PanelSwitchHelper.jar
       - http://mvn.leancloud.cn/nexus/content/repositories/public/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
       - http://mvn.gt.igexin.com/nexus/content/repositories/releases/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
     Required by:
         project :desk

**Comment by lh1241698502** [comment]
> > Could not resolve all files for configuration ':desk:lezhuDevelopmentDebugRuntimeClasspath'.
> > Could not find com.github.DSAppTeam:PanelSwitchHelper:v1.5.4.
> > Searched in the following locations:
> > - https://repo.maven.apache.org/maven2/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
> > - https://maven.aliyun.com/nexus/content/groups/public/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
> > - https://maven.aliyun.com/nexus/content/repositories/releases/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
> > - https://mvn.getui.com/nexus/content/repositories/releases/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
> > - https://dl.google.com/dl/android/maven2/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
> > - https://www.jitpack.io/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
> > - https://gitee.com/goweii/maven-repository/raw/master/releases/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
> > - https://repo1.maven.org/maven2/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
> > - file:/Users/hailong/StudioProjects/lezhu2/lezhu-common/libs/PanelSwitchHelper-v1.5.4.jar
> > - file:/Users/hailong/StudioProjects/lezhu2/lezhu-common/libs/PanelSwitchHelper.jar
> > - http://mvn.leancloud.cn/nexus/content/repositories/public/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
> > - http://mvn.gt.igexin.com/nexus/content/repositories/releases/com/github/DSAppTeam/PanelSwitchHelper/v1.5.4/PanelSwitchHelper-v1.5.4.pom
> > Required by:
> > project :desk

去掉1.5.4前面那个v就行了
