### ISSUE TITLE
ViewPger2+Fragment切换时，PanelSwitchLayout中布局不显示

### ISSUE THREAD

**Issue by mengyuqiang** [DSAppTeam/PanelSwitchHelper#197]
在直播场景中，使用ViewPager2+Fragment（一共三个Fragment），通过上下滑动实现三个直播间的切换，在Fragment中使用PanelSwitchLayout，用于管理直播间底部的EditText和其他按钮，上下滑动切换Fragment时，一切正常，但是若在某个Fragment中选中输入框弹起/隐藏软键盘后，再切换到其他Fragment时，其他Fragment中的PanelSwitchLayout中的按钮都会不显示，在HONOR X10/realme/oppo等手机上都有这种情况
正常情况：
![1893ea8f08d8837933049d1a0309098](https://github.com/DSAppTeam/PanelSwitchHelper/assets/132742906/9757b30a-fc09-4013-92be-064e895e7ff1)
异常情况：
![75e183c6e77002ebfce44701bbccc50](https://github.com/DSAppTeam/PanelSwitchHelper/assets/132742906/d920da0b-26ea-4dcd-8479-d49c80a0ddbd)

上面是ViewPager2竖直滑动，将orientation属性改为横向后，不会出现上面的异常情况

**Comment by mengyuqiang** [comment]
我下载了PanelSwitchLayout的Demo，添加了一个使用ViewPager2的Activity，ViewPager2加载三个Demo中的ChatFragment，方向为垂直，ChatFragment未作修改，上下切换时，只有第一个ChatFragment中有数据和布局，后面两个只有标题栏 ，ViewPager2换成横向时，就是正常的

**Comment by HeroZ-Dodge** [comment]
你好，这个应用场景我们还没有兼容过，我们会考虑在后续的版本中逐渐完善这些场景

**Comment by HeroZ-Dodge** [comment]
最新demo中提交了ViewPager、ViewPager2的用例，可以参考下对应的实现。需要注意的是Fragment在切换的时候，会在合适的生命周期中初始化 / 回收 PanelSwitchLayout的监听器
