### ISSUE TITLE
弹出软键盘时崩溃

### ISSUE THREAD

**Issue by Movingbricks** [DSAppTeam/PanelSwitchHelper#198]
Androidx版本：是
PanelSwitchHelper版本：v1.5.4
手机型号: 魅族
手机系统版本： Android 11
问题描述：弹出软键盘时崩溃,代码混淆后会崩溃，不混淆的话没有问题

![WX20230716-155756@2x](https://github.com/DSAppTeam/PanelSwitchHelper/assets/22463456/eb7439fd-7a4a-4044-9f5c-9c0be2a1aa56)

**Comment by HeroZ-Dodge** [comment]
有没有尝试过修改下混淆规则来规避这个问题，你尝试把androidx的代码不添加混淆，同时把 WindowInsetsAnimationCompat.Callback 这个类的实现类不进行混淆试试
