### ISSUE TITLE
点击表情面板时，EditText焦点丢失，光标不显示

### ISSUE THREAD

**Issue by aheven** [DSAppTeam/PanelSwitchHelper#201]
点击面板输入表情，然后点击RecyclerView使EditText丢失焦点，再次点击表情按钮时，EditText焦点丢失，光标不显示

**Comment by 15359947959** [comment]
收到了，辛苦啦

**Comment by HeroZ-Dodge** [comment]
PanelSwitchLayout控件中添加了focusAndShowSelection方法，参考demo中ChatFragment中的示例
