### ISSUE TITLE
全屏视频播放的情景，输入框面板基于PopWindow实现，假如是点击外部的表情按钮唤起 面板，直接显示表情面板该怎样实现？

### ISSUE THREAD

**Issue by Zeng-Ke** [DSAppTeam/PanelSwitchHelper#206]
全屏视频播放的情景，输入框面板基于PopWindow实现，假如是点击外部的表情按钮唤起 面板，直接显示表情面板该怎样实现？（类似demo中的B栈，底部唤醒按钮多一个表情按钮直接唤起面板）

**Comment by HeroZ-Dodge** [comment]
你参考demo添加表情面板，添加切换按钮就应该就可以实现了
