### ISSUE TITLE
使用 BaseDialogFragment 并设置高度后，底部输入框部分不展示，或者展示不全

### ISSUE THREAD

**Issue by HLQ-Struggle** [DSAppTeam/PanelSwitchHelper#207]
复线场景：修改 Demo 中 ChatDialogFragment 的高度：

/**
     * dialogfragment基于dialog实现，需要设置以下代码
     */
    @Override
    public void onStart() {
        super.onStart();
        // ...
         int height = (int) (getResources().getDisplayMetrics().heightPixels * 0.65);    // <--- 这里设置高度为 65%
       // ...
    } 

展示效果如下：
![image](https://img.xwyue.com/i/2024/01/27/65b48dd21eb37.png)

设备类型：
![image](https://img.xwyue.com/i/2024/01/27/65b48e0d312da.png)

弹出日志：
`
WARNING: Logcat was not cleared on the device itself because of a bug in Android 8.0 (Oreo).
2024-01-27 12:56:19.629 29115-29120 zygote64                com.example.demo                     I  Do full code cache collection, code=503KB, data=343KB
2024-01-27 12:56:19.629 29115-29115 LogTracker              com.example.demo                     D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :764
2024-01-27 12:56:19.630 29115-29120 zygote64                com.example.demo                     I  After code cache collection, code=503KB, data=301KB
2024-01-27 12:56:19.667 29115-29115 LogTracker              com.example.demo                     D  PanelSwitchLayout#onGlobalLayout => 界面每一次变化的信息回调 
                                                                                                    windowSoftInputMode                                = 19 
                                                                                                    currentPanelSwitchLayoutVisible                    = true 
                                                                                                    screenHeight                                       = 2040 
                                                                                                    contentHeight                                      = 1848 
                                                                                                    isFullScreen                                       = false 
                                                                                                    isNavigationBarShown                               = true 
                                                                                                    deviceStatusBarH                                   = 72 
                                                                                                    deviceNavigationBarH                               = 120 
                                                                                                    systemInset                                        = left(72) top(0) right(0) bottom(120) 
                                                                                                    inset                                              = left(0) top(72) right(0) bottom(120) 
                                                                                                    currentSystemInfo                                  = statusBarH : 72, navigationBarH : 120 全面屏手势虚拟栏H : 0 
                                                                                                    currentSystemH                                     = 192 
                                                                                                    minLimitCloseKeyboardH                             = 120 
                                                                                                    minLimitOpenKeyboardH                              = 300 
                                                                                                    lastKeyboardH                                      = 0 
                                                                                                    currentKeyboardInfo                                = keyboardH : 0, realKeyboardH : 0, isShown : false 
2024-01-27 12:56:19.731 29115-29115 LogTracker              com.example.demo                     D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :764
2024-01-27 12:56:19.731 29115-29115 LogTracker              com.example.demo                     D  PanelSwitchLayout#onLayout =>  getContentContainerTop  :0
2024-01-27 12:56:19.798 29115-29120 zygote64                com.example.demo                     I  Do partial code cache collection, code=503KB, data=312KB
2024-01-27 12:56:19.799 29115-29120 zygote64                com.example.demo                     I  After code cache collection, code=503KB, data=312KB
2024-01-27 12:56:19.799 29115-29120 zygote64                com.example.demo                     I  Increasing code cache capacity to 2MB
2024-01-27 12:56:19.808 29115-29115 LogTracker              com.example.demo                     D  PanelSwitchLayout#onLayout => 界面每一次 layout 的信息回调 
                                                                                                    layoutInfo                                         = onLayout(changed : true , l : 0  , t : 150 , r : 1080 , b : 1248) 
                                                                                                    currentPanelState                                  = 收起所有输入源 
                                                                                                    isPad                                              = false 
                                                                                                    isFullScreen                                       = false 
                                                                                                    isPortrait                                         = true 
                                                                                                    isNavigationShown                                  = true 
                                                                                                    screenH (static,include SystemUI)                  = 2040 
                                                                                                    screenH (static,exclude SystemUI)                  = 1920 
                                                                                                    screenH (dynamic,exclude SystemUI)                 = 1848 
                                                                                                    localLocation[y]                                   = 522 
                                                                                                    toolbarH                                           = 168 
                                                                                                    StatusBarH                                         = 72 
                                                                                                    NavigationBarH                                     = 120 
                                                                                                    layout Location                                    = (0,522) 
                                                                                                    paddingTop                                         = 0 
                                                                                                    keyboardH                                          = 764 
                                                                                                    ContentContainerTop                                = 0 
                                                                                                    ContentContainerH                                  = 1398 
                                                                                                    PanelContainerTop                                  = 1398 
                                                                                                    PanelContainerH                                    = 764 
                                                                                                    changeBounds                                       = true 
                                                                                                    reverseResetState                                  = false 
                                                                                                    contentContainer Layout                            = (0,0,1080,1398) 
                                                                                                    panelContainer Layout                              = (0,1398,1080,2162) 
2024-01-27 12:56:19.809 29115-29115 View                    com.example.demo                     W  requestLayout() improperly called by com.effective.android.panel.view.content.LinearContentContainer{5964cc0 VFE...... ......ID 0,0-1080,1398 #7f070079 app:id/content_view} during layout: running second layout pass
2024-01-27 12:56:19.814 29115-29115 LogTracker              com.example.demo                     D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :764
2024-01-27 12:56:19.814 29115-29115 LogTracker              com.example.demo                     D  PanelSwitchLayout#onLayout =>  getContentContainerTop  :0
2024-01-27 12:56:19.828 29115-29115 LogTracker              com.example.demo                     D  PanelSwitchLayout#onLayout => 界面每一次 layout 的信息回调 
                                                                                                    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 150 , r : 1080 , b : 1248) 
                                                                                                    currentPanelState                                  = 收起所有输入源 
                                                                                                    isPad                                              = false 
                                                                                                    isFullScreen                                       = false 
                                                                                                    isPortrait                                         = true 
                                                                                                    isNavigationShown                                  = true 
                                                                                                    screenH (static,include SystemUI)                  = 2040 
                                                                                                    screenH (static,exclude SystemUI)                  = 1920 
                                                                                                    screenH (dynamic,exclude SystemUI)                 = 1848 
                                                                                                    localLocation[y]                                   = 522 
                                                                                                    toolbarH                                           = 168 
                                                                                                    StatusBarH                                         = 72 
                                                                                                    NavigationBarH                                     = 120 
                                                                                                    layout Location                                    = (0,522) 
                                                                                                    paddingTop                                         = 0 
                                                                                                    keyboardH                                          = 764 
                                                                                                    ContentContainerTop                                = 0 
                                                                                                    ContentContainerH                                  = 1398 
                                                                                                    PanelContainerTop                                  = 1398 
                                                                                                    PanelContainerH                                    = 764 
                                                                                                    changeBounds                                       = false 
                                                                                                    contentContainer Layout                            = (0,0,1080,1398) 
                                                                                                    panelContainer Layout                              = (0,1398,1080,2162) 
2024-01-27 12:56:19.853 29115-29115 View                    com.example.demo                     W  requestLayout() improperly called by android.widget.LinearLayout{a65034a V.E...... ........ 0,1035-1080,1155} during second layout pass: posting in next frame
2024-01-27 12:56:19.854 29115-29115 View                    com.example.demo                     W  requestLayout() improperly called by android.widget.LinearLayout{93f22bb V.E...... ........ 0,1200-1080,1320} during second layout pass: posting in next frame
2024-01-27 12:56:19.869 29115-29115 LogTracker              com.example.demo                     D  PanelSwitchLayout#onLayout =>  getCompatPanelHeight  :764
2024-01-27 12:56:19.869 29115-29115 LogTracker              com.example.demo                     D  PanelSwitchLayout#onLayout =>  getContentContainerTop  :0
2024-01-27 12:56:19.872 29115-29115 LogTracker              com.example.demo                     D  PanelSwitchLayout#onLayout => 界面每一次 layout 的信息回调 
                                                                                                    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 150 , r : 1080 , b : 1248) 
                                                                                                    currentPanelState                                  = 收起所有输入源 
                                                                                                    isPad                                              = false 
                                                                                                    isFullScreen                                       = false 
                                                                                                    isPortrait                                         = true 
                                                                                                    isNavigationShown                                  = true 
                                                                                                    screenH (static,include SystemUI)                  = 2040 
                                                                                                    screenH (static,exclude SystemUI)                  = 1920 
                                                                                                    screenH (dynamic,exclude SystemUI)                 = 1848 
                                                                                                    localLocation[y]                                   = 522 
                                                                                                    toolbarH                                           = 168 
                                                                                                    StatusBarH                                         = 72 
                                                                                                    NavigationBarH                                     = 120 
                                                                                                    layout Location                                    = (0,522) 
                                                                                                    paddingTop                                         = 0 
                                                                                                    keyboardH                                          = 764 
                                                                                                    ContentContainerTop                                = 0 
                                                                                                    ContentContainerH                                  = 1398 
                                                                                                    PanelContainerTop                                  = 1398 
                                                                                                    PanelContainerH                                    = 764 
                                                                                                    changeBounds                                       = false 
                                                                                                    contentContainer Layout                            = (0,0,1080,1398) 
                                                                                                    panelContainer Layout                              = (0,1398,1080,2162) 

`

**Comment by HLQ-Struggle** [comment]
设备类型：小米 Mix
Android 版本：8.0.0

**Comment by HeroZ-Dodge** [comment]
我们没有针对这种不铺满屏幕的场景做适配，在计算控件高度的时候都是用屏幕高度 - 系统控件高度（状态栏、导航栏等）来计算的。

**Comment by HLQ-Struggle** [comment]
> 我们没有针对这种不铺满屏幕的场景做适配，在计算控件高度的时候都是用屏幕高度 - 系统控件高度（状态栏、导航栏等）来计算的。

查看源码后，发现
