### ISSUE TITLE
android 14 无法唤起相机拍照

### ISSUE THREAD

**Issue by dongqiCyberflow** [DSAppTeam/PanelSwitchHelper#209]
pictureSelector.openCamera(SelectMimeType.ofAll())
                    .setSelectMinFileSize(1)
                    .setSelectMaxFileSize(1)
                    .setSelectMaxFileSize(20000L)
                    .setSelectMinFileSize(1)
                    .forResult(object : OnResultCallbackListener<LocalMedia?> {
                        override fun onResult(result: ArrayList<LocalMedia?>) {
                            onSendImage(result)
                        }

                        override fun onCancel() {}
                    })
                    
                    没反应，权限也都给了，原因是
                     if (cameraIntent.resolveActivity(getActivity().getPackageManager()) != null) { 这个判断没进来

**Comment by 15359947959** [comment]
收到了，辛苦啦
