### ISSUE TITLE
输入框无法长按弹出系统的全选复制粘贴ContextMenu

### ISSUE THREAD

**Issue by zzz-97** [DSAppTeam/PanelSwitchHelper#210]
Demo中的popwindow就是这样

![QQ图片20240624092451](https://github.com/DSAppTeam/PanelSwitchHelper/assets/29701023/cc84a298-6bea-470e-9b1c-aa93e2a7498a)

怎么解决呢

**Comment by 15359947959** [comment]
收到了，辛苦啦
