### ISSUE TITLE
支持Android11新的API

### ISSUE THREAD

**Issue by limuyang2** [DSAppTeam/PanelSwitchHelper#97]
目前的动画会在Android11上有问题，
后来发现Android11出了新的API。

官方介绍如下：

> 同步 IME 切换效果  - 这是一组全新的 API，让您可以在 IME (输入法编辑器，也叫软键盘) 和系统栏进出屏幕时同步调整应用中的内容，从而更轻松地创建出自然、直观、流畅的 IME 切换效果。为了确保切换时做到逐帧精确，新的 WindowInsetsAnimation.Callback API 会在系统栏或 IME 移动时逐帧告知应用边衬区的变化。此外，您可以通过新的 WindowInsetsAnimationController API 控制系统 UI，包括系统栏、IME、沉浸模式等。阅读 这篇博文 了解更多。

[Android 11 正式发布 | 开发者们的舞台已就绪](https://juejin.im/post/6870400991200542727)

**Comment by limuyang2** [comment]
最后感慨一句，谷歌终于出API了，当时我做iOS的时候，也有类似的api，就可以做到和键盘逐帧精确的同速，不需要动画。

**Comment by YummyLau** [comment]
@limuyang2 你说的动画在Android11有问题，具体表现是怎样的，android 11 是兼容的，方便提供下视频效果及log吗
Andriod11的api，最近考虑适配。

**Comment by lic2050** [comment]
Android11 同步 IME 动画
https://juejin.im/post/6844904104129462279#heading-1

**Comment by YummyLau** [comment]
@lic2050 目前还有很多适配问题需要解决。

**Comment by liangjingkanji** [comment]
看还没人实现我就自己实现了一个: [soft-input-event](https://github.com/liangjingkanji/soft-input-event)

> 对于部分机型MIUI/鸿蒙的确存在平滑无效, 所以兼容使用旧的方案处理
